[47.129154205] 2018-01-07 14:02:35,418 - INFO - launcher: Starting sanity checks
[48.131704330] 2018-01-07 14:02:35,419 - INFO - launcher: Checking for Python 3.5+
[48.131704330] 2018-01-07 14:02:35,419 - INFO - launcher: Checking console encoding
[48.131704330] 2018-01-07 14:02:35,419 - INFO - launcher: Setting console encoding to UTF-8
[48.633098602] 2018-01-07 14:02:35,420 - INFO - launcher: Ensuring we're in the right environment
[49.134254456] 2018-01-07 14:02:35,420 - INFO - launcher: Adding local bins/ folder to path
[49.635648727] 2018-01-07 14:02:35,421 - INFO - launcher: Required checks passed.
[50.137042999] 2018-01-07 14:02:35,421 - INFO - launcher: Optional checks passed.

######################### PRE-RUN SANITY CHECKS PASSED #########################

[5.4572937488555908] 2018-01-07 14:02:40,829 - DEBUG - musicbot.config | In config.py::MainThread(10384), line 234 in find_autoplaylist: Copying _autoplaylist.txt to autoplaylist.txt
[5.4577953815460205] 2018-01-07 14:02:40,829 - INFO - musicbot.permissions | In permissions.py::MainThread(10384), line 34 in __init__: Permissions file not found, copying example_permissions.ini
[5.6258292198181152] 2018-01-07 14:02:40,997 - DEBUG - musicbot.bot | In bot.py::MainThread(10384), line 213 in _setup_logging: Set logging level to INFO
[5.6263306140899658] 2018-01-07 14:02:40,998 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 80 in __init__: =========== MusicBot (version 1.9.6_1) ===========
[5.6268322467803955] 2018-01-07 14:02:40,998 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 86 in __init__: Loaded autoplaylist with 2531 entries
[5.628336668] launcher-INFO: Connecting
[8.7347552776336670] 2018-01-07 14:02:44,106 - DEBUG - musicbot.bot | In bot.py::MainThread(10384), line 1011 in on_ready: Connection established, ready to go.
[8.7347552776336670] 2018-01-07 14:02:44,106 - DEBUG - musicbot.bot | In bot.py::MainThread(10384), line 324 in _cache_app_info: Caching app info
[8.8080112934112549] 2018-01-07 14:02:44,179 - DEBUG - musicbot.bot | In bot.py::MainThread(10384), line 828 in _scheck_ensure_env: Ensuring data folders exist
[8.8090140819549561] 2018-01-07 14:02:44,180 - DEBUG - musicbot.bot | In bot.py::MainThread(10384), line 844 in _scheck_server_permissions: Checking server permissions
[8.8090140819549561] 2018-01-07 14:02:44,180 - DEBUG - musicbot.bot | In bot.py::MainThread(10384), line 848 in _scheck_autoplaylist: Auditing autoplaylist
[8.8095149993896484] 2018-01-07 14:02:44,181 - DEBUG - musicbot.bot | In bot.py::MainThread(10384), line 852 in _scheck_configs: Validating config
[8.8095149993896484] 2018-01-07 14:02:44,181 - DEBUG - musicbot.config | In config.py::MainThread(10384), line 155 in async_validate: Validating options...
[8.8095149993896484] 2018-01-07 14:02:44,181 - DEBUG - musicbot.config | In config.py::MainThread(10384), line 169 in async_validate: Acquired owner id via API
[8.8100163936614990] 2018-01-07 14:02:44,181 - DEBUG - musicbot.bot | In bot.py::MainThread(10384), line 855 in _scheck_configs: Validating permissions config
[8.8100163936614990] 2018-01-07 14:02:44,181 - DEBUG - musicbot.permissions | In permissions.py::MainThread(10384), line 59 in async_validate: Validating permissions...
[8.8105180263519287] 2018-01-07 14:02:44,182 - DEBUG - musicbot.permissions | In permissions.py::MainThread(10384), line 63 in async_validate: Fixing automatic owner group
[8.8105180263519287] 2018-01-07 14:02:44,182 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 1022 in on_ready: Connected to Discord!
[8.8110189437866211] 2018-01-07 14:02:44,182 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 1032 in on_ready: Bot:   399651000677302273/mybot1#8720 [BOT]
[8.8115210533142090] 2018-01-07 14:02:44,183 - WARNING - musicbot.bot | In bot.py::MainThread(10384), line 1053 in on_ready: Owner unknown, bot is not on any servers.
[8.8125240802764893] 2018-01-07 14:02:44,184 - WARNING - musicbot.bot | In bot.py::MainThread(10384), line 1059 in on_ready: To make the bot join a server, paste this link in your browser. 
Note: You should be logged into your main account and have 
manage server permissions on the server you want the bot to join.
  https://discordapp.com/oauth2/authorize?client_id=399651000677302273&scope=bot&permissions=70380544
[8.8130252361297607] 2018-01-07 14:02:44,184 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 1088 in on_ready: Not bound to any text channels
[8.8135263919830322] 2018-01-07 14:02:44,185 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 1114 in on_ready: Not autojoining any voice channels
[8.8140270709991455] 2018-01-07 14:02:44,185 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 1118 in on_ready: Options:
[8.8150305747985840] 2018-01-07 14:02:44,186 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 1120 in on_ready:   Command prefix: !
[8.8155314922332764] 2018-01-07 14:02:44,187 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 1121 in on_ready:   Default volume: 25%
[8.8160331249237061] 2018-01-07 14:02:44,187 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 1123 in on_ready:   Skip threshold: 4 votes or 50%
[8.8165349960327148] 2018-01-07 14:02:44,188 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 1124 in on_ready:   Now Playing @mentions: Disabled
[8.8170361518859863] 2018-01-07 14:02:44,188 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 1125 in on_ready:   Auto-Summon: Enabled
[8.8175377845764160] 2018-01-07 14:02:44,189 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 1126 in on_ready:   Auto-Playlist: Enabled
[8.8180375099182129] 2018-01-07 14:02:44,189 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 1127 in on_ready:   Auto-Pause: Enabled
[8.8235535621643066] 2018-01-07 14:02:44,195 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 1128 in on_ready:   Delete Messages: Enabled
[8.8245561122894287] 2018-01-07 14:02:44,196 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 1130 in on_ready:     Delete Invoking: Disabled
[8.8250579833984375] 2018-01-07 14:02:44,196 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 1131 in on_ready:   Debug Mode: Disabled
[8.8255591392517090] 2018-01-07 14:02:44,197 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 1132 in on_ready:   Downloaded songs will be saved
[47.6668646335601807] 2018-01-07 14:03:23,038 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 2628 in on_server_join: Bot has been joined server: lol
[47.6683688163757324] 2018-01-07 14:03:23,040 - DEBUG - musicbot.bot | In bot.py::MainThread(10384), line 2641 in on_server_join: Creating data folder for server 399351006460248074
[56.0610225200653076] 2018-01-07 14:03:31,432 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(10384), line 2564 in on_voice_state_update: Voice state update for 321866366833524737/Saber#6449 on lol/General -> [CONNECT]
[57.4159493446350098] 2018-01-07 14:03:32,787 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(10384), line 2564 in on_voice_state_update: Voice state update for 185978196070629386/oscdoza#6890 on lol/General -> [CONNECT]
[83.1910045146942139] 2018-01-07 14:03:58,562 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 2395 in on_message: 321866366833524737/Saber#6449: !summon
[83.1930105686187744] 2018-01-07 14:03:58,564 - ERROR - musicbot.bot | In bot.py::MainThread(10384), line 2515 in on_message: Error in summon: PermissionsError: You don't have permission to use that command.
Reason: This command is not enabled for your group (Default).
Traceback (most recent call last):
  File "C:\Users\oscdo\~\MusicBot\musicbot\bot.py", line 2477, in on_message
    expire_in=20)
musicbot.exceptions.PermissionsError: This command is not enabled for your group (Default).
[103.9631152153015137] 2018-01-07 14:04:19,334 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 2395 in on_message: 185978196070629386/oscdoza#6890: !summon
[103.9646193981170654] 2018-01-07 14:04:19,336 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 1804 in cmd_summon: Joining lol/General
[103.9651196002960205] 2018-01-07 14:04:19,336 - DEBUG - musicbot.bot | In bot.py::MainThread(10384), line 437 in get_voice_client: Connection attempt 1 to General
[103.9651196002960205] 2018-01-07 14:04:19,336 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(10384), line 376 in join_voice_channel: (join_voice_channel) creating futures
[103.9651196002960205] 2018-01-07 14:04:19,336 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(10384), line 382 in join_voice_channel: (join_voice_channel) setting voice state
[103.9656209945678711] 2018-01-07 14:04:19,337 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(10384), line 385 in join_voice_channel: (join_voice_channel) waiting for session id
[104.0542747974395752] 2018-01-07 14:04:19,426 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(10384), line 2564 in on_voice_state_update: Voice state update for 399651000677302273/mybot1#8720 on lol/General -> [JOIN, CONNECT]
[104.0547766685485840] 2018-01-07 14:04:19,426 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 2575 in on_voice_state_update: 399651000677302273/mybot1#8720 has joined lol/General
[104.0557785034179688] 2018-01-07 14:04:19,427 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(10384), line 389 in join_voice_channel: (join_voice_channel) waiting for voice data
[104.0988225936889648] 2018-01-07 14:04:19,470 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(10384), line 403 in join_voice_channel: (join_voice_channel) connecting...
[104.3922469615936279] 2018-01-07 14:04:19,764 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(10384), line 415 in join_voice_channel: (join_voice_channel) connection successful
[104.3922469615936279] 2018-01-07 14:04:19,764 - DEBUG - musicbot.bot | In bot.py::MainThread(10384), line 463 in get_voice_client: Connected in 0.4s
[104.3927483558654785] 2018-01-07 14:04:19,764 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 464 in get_voice_client: Connected to lol/General
[104.4119029045104980] 2018-01-07 14:04:19,783 - VOICEDEBUG - musicbot.player | In player.py::MainThread(10384), line 311 in websocket_check: Starting websocket check loop for lol
[110.6928734779357910] 2018-01-07 14:04:26,064 - INFO - musicbot.entry | In entry.py::MainThread(10384), line 219 in _really_download: Download started: https://youtube.com/watch?v=Lx2zzIkaUZQ
[113.4957637786865234] 2018-01-07 14:04:28,867 - INFO - musicbot.entry | In entry.py::MainThread(10384), line 226 in _really_download: Download complete: https://youtube.com/watch?v=Lx2zzIkaUZQ
[113.5027828216552734] 2018-01-07 14:04:28,874 - FFMPEG - musicbot.player | In player.py::MainThread(10384), line 268 in _play: Creating player with options: -nostdin -vn audio_cache\youtube-Lx2zzIkaUZQ-Future_Bass_-_Conro_-_The_Saint_Monstercat_Release.webm
[113.5208332538604736] 2018-01-07 14:04:28,892 - DEBUG - musicbot.bot | In bot.py::MainThread(10384), line 781 in serialize_queue: Serializing queue for 399351006460248074
[125.6716339588165283] 2018-01-07 14:04:41,043 - INFO - musicbot.bot | In bot.py::MainThread(10384), line 2395 in on_message: 185978196070629386/oscdoza#6890: !disconnect
[125.7853696346282959] 2018-01-07 14:04:41,157 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(10384), line 2564 in on_voice_state_update: Voice state update for 399651000677302273/mybot1#8720 on lol/General -> [DISCONNECT]
